### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by leongrdic** [buttercup/buttercup-desktop#1009]
The way I have used buttercup for the longest time is just alt+tab to its window, unlock the vault using the shortcut Ctrl+1, navigate to the field I wanted to find using Ctrl+F and then copy the password with Ctrl+C. Now none of these shortcuts work as they did before.
The Ctrl+F does work but it keeps the last search query with the cursor set to end, instead of e.g. selecting the last query so that typing in a new one doesn't just append to the last one.

**Comment by perry-mitchell** [comment]
Good points, and sorry for the inconvenience. I'll summarise here:

1. On search appear, select whole term for easy replacement
2. Hot-key for unlocking current vault
3. Hot-keys for switching vaults
4. Keyboard controls for navigating the UI (this should be implemented in the [UI library](https://github.com/buttercup/ui)

**Comment by leongrdic** [comment]
Also the Ctrl+C shortcut to actually copy the password!

**Comment by ldexterldesign** [comment]
macOS shortcuts appear to be broken (e.g. cmd+m, cmd+h, cmd+w, although cmd+q works) - anyone else suffering this?

Cheers

**Comment by BlackGopher2030** [comment]
In buttercup when i press ctrl + f to search for an entry i get nothing, the search bar does not appear. It was appearing before when i was using gnome or xfce. But now i use KDE.

I do not know if the problem is from KDE environment or buttercup itself. I tried to use the filter icon in the Documents column (Entries column) and it searches well. Though when i searched using the letters "ver" i got this error:
```

Error
A fatal error has occurred - we're sorry this has happened. Please check out the details below in case they help diagnose the issue:

TypeError: Cannot read property 'substring' of undefined
    at Nn (file:///tmp/.mount_Butter210614/resources/app.asar/build/renderer/index.js:274:20)
    at div
    at t (file:///tmp/.mount_Butter210614/resources/app.asar/build/renderer/index.js:2:1221345)
    at t (file:///tmp/.mount_Butter210614/resources/app.asar/build/renderer/index.js:2:1221832)
    at div
    at styled.div (file:///tmp/.mount_Butter210614/resources/app.asar/build/renderer/index.js:524:1503286)
    at div
    at styled.div (file:///tmp/.mount_Butter210614/resources/app.asar/build/renderer/index.js:524:1503286)
    at Qn (file:///tmp/.mount_Butter210614/resources/app.asar/build/renderer/index.js:331:2406)
    at div
    at s (file:///tmp/.mount_Butter210614/resources/app.asar/build/renderer/index.js:2:1158775)
    at div
    at t (file:///tmp/.mount_Butter210614/resources/app.asar/build/renderer/index.js:2:1160256)
    at div
    at s (file:///tmp/.mount_Butter210614/resources/app.asar/build/renderer/index.js:2:1158775)
    at div
    at t (file:///tmp/.mount_Butter210614/resources/app.asar/build/renderer/index.js:2:1160256)
    at div
    at styled.div (file:///tmp/.mount_Butter210614/resources/app.asar/build/renderer/index.js:524:1503286)
    at Ha
    at De (file:///tmp/.mount_Butter210614/resources/app.asar/build/renderer/index.js:215:6335)
    at Ne (file:///tmp/.mount_Butter210614/resources/app.asar/build/renderer/index.js:524:1501382)
    at t.VaultEditor (file:///tmp/.mount_Butter210614/resources/app.asar/build/renderer/index.js:620:1981)
    at h (file:///tmp/.mount_Butter210614/resources/app.asar/build/renderer/index.js:587:45)
    at div
    at styled.div (file:///tmp/.mount_Butter210614/resources/app.asar/build/renderer/index.js:524:1503286)
    at t.SearchProvider (file:///tmp/.mount_Butter210614/resources/app.asar/build/renderer/index.js:683:1708)
    at div
```

**Comment by ldexterldesign** [comment]
Hi @BlackGopher2030,

cmd+f OK for me in macOS 🤷‍♂️

Regards

**Comment by BlackGopher2030** [comment]
That's weird, i just downloaded buttercup version `1.20.4` and the `ctrl + f` works fine, when i press the shortcut the search bar pops up. But still it does not work in version `2.2.0`. The search bar is very imp, i have lots of entries, i will be doomed if i keep scrolling.

**Comment by perry-mitchell** [comment]
>The search bar is very imp, i have lots of entries, i will be doomed if i keep scrolling.

That's the whole point of search though - narrowing the results until you find what you're looking for. If you intend on scrolling many 10s if entries, then search isn't going to help you. Some kind of view-all feature might.

**Comment by perry-mitchell** [comment]
> On search appear, select whole term for easy replacement

Not sure how easy this will be to implement. Let's follow this particular feature in #1025

**Comment by leongrdic** [comment]
hi! one part of this issue has been solved but there are two really important shortcuts still missing! ctrl+number (for selecting the vault to unlock) and even more important ctrl+c for copying the password once i find an entry i want.

**Comment by ViacheslavKruhlov** [comment]
I want to share positive experience from another password manager app - using `Ctrl + B` for copying login and `Ctrl + C` for copying password (like it is now)

**Comment by ldexterldesign** [comment]
🙏😩

**Comment by ldexterldesign** [comment]
👋 @perry-mitchell,

While I was skimming the [Electron docs] I recalled [Vivaldi] had/has a similar issue so I think this may be best addressed upstream (i.e. with Electron for macOS) - what do you think?

Can anyone confirm how minimise shortcut behaves on non-macOS platforms?

Hope to hear back

Cheers

[Electron docs]: https://www.electronjs.org/docs/latest/tutorial/keyboard-shortcuts
[Vivaldi]: https://forum.vivaldi.net/topic/43197/research-possible-minimise-window-bug?_=1661810582003&lang=en-GB
