### ISSUE TITLE
AppImage starts with blank screen on Linux Mint

### ISSUE THREAD

**Issue by jnweiger** [buttercup/buttercup-desktop#1081]
Seen with both, the appimage of version 2.8.3 and 2.10.0 
Running on Linux Mint 20.2 -- Buttercup was running happily on the system before doing an apt upgrade yesterday. That upgrade was massive, though.
Since then, buttercup fails to start properly:

* Start the appimage, the window appears, with menues, but otherwise all white.
* Quit and open devtools works, but the screen remains blank even after force refresh.

![image](https://user-images.githubusercontent.com/1108546/130779202-95257a49-95ee-460b-a602-31bea495cfe7.png)

The console output from 2.10.0 is:
```
$ Buttercup-linux-x64.AppImage 
[INF] 11:01:39: Application starting
[INF] 11:01:39: Registering protocol: buttercup
[ERR] 11:01:39: Failed registering protocol: buttercup
[INF] 11:01:39: Application ready
[INF] 11:01:39: Application session started: 2021-08-25T11:01:39.930Z
[INF] 11:01:39: Logs location: /home/testy/.local/state/Buttercup-nodejs/buttercup-desktop.log
[INF] 11:01:39: System locale detected: en-US
[INF] 11:01:39: Starting with language: en-US
[INF] 11:01:39: Updated search records for 0 vaults
[INF] 11:01:39: Updated search records for 0 vaults
[INF] 11:01:39: Updated search records for 0 vaults
[INF] 11:01:39: Updated search records for 0 vaults
[INF] 11:01:40: Applying theme source: system
[INF] 11:01:40: Starting file host (key exists: true)
[INF] 11:01:40: Portable mode: no
[INF] 11:01:40: Biometrics: yes
[INF] 11:01:40: Initialisation completed
[176044:0825/130140.122115:FATAL:memory_linux.cc(37)] Out of memory.
[176086:0825/130140.432434:FATAL:memory_linux.cc(37)] Out of memory.
[176117:0825/130140.641545:FATAL:memory_linux.cc(37)] Out of memory.
[176131:0825/130140.802271:FATAL:memory_linux.cc(37)] Out of memory.
[176140:0825/130140.908136:FATAL:memory_linux.cc(37)] Out of memory.
[176149:0825/130141.014918:FATAL:memory_linux.cc(37)] Out of memory.
[INF] 11:01:42: Checking for updates
Checking for update
Update for version 2.10.0 is not available (latest version: 2.10.0, downgrade is disallowed).
[INF] 11:01:43: No update available
(node:176003) UnhandledPromiseRejectionWarning: Error: Timed-out waiting for window to load
    at Timeout._onTimeout (/tmp/.mount_ButteroskryJ/resources/app.asar/build/main/services/windows.js:62:53)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `buttercup --trace-warnings ...` to show where the warning was created)
(node:176003) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:176003) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Same with version 2.8.3, except that 2.10.0 is correctly announced as an available update.

My machine has 5 GB of RAM used out of a total of 16GB. All disk partitions have several GB free too. 
Not sure what I can do about the 'Out of memory' errors there.

**Comment by jnweiger** [comment]
Workaround:
* Start buttercup from the shell in the background `bin/Buttercup-linux-x64.AppImage &`
* Close the window (using the x, or the Buttercup -> Close window menue entry)
* Start a second copy of buttercup from the shell `bin/Buttercup-linux-x64.AppImage`
* The second copy prints 4 lines and exits immediately
```
[INF] 14:45:34: Application starting
[INF] 14:45:34: Registering protocol: buttercup
[ERR] 14:45:34: Failed registering protocol: buttercup
[INF] 14:45:34: Application ready
```
* A fully functional buttercup window appears.

**Comment by perry-mitchell** [comment]
This looks telling: `UnhandledPromiseRejectionWarning: Error: Timed-out waiting for window to load`

Not sure what the issue could be, however.

**Comment by perry-mitchell** [comment]
As I haven't heard of more people experiencing this issue, I'm going to have to close it. There's nothing actionable here for me - if this changes I'll gladly reopen.
