### ISSUE TITLE
Error while filtering registers

### ISSUE THREAD

**Issue by manueldeljesus** [buttercup/buttercup-desktop#1111]
I have imported a CSV exported from Firefox and everything seems to be working. However, I would like to clean a little bit, as it seems that there are multiple entries for the same sites with old passwords.

I try to filter the entrances in the imported group (search term: identidad) but when I type the fourth letter (n) of the search term I get the following error:

``` TypeError: Cannot read properties of undefined (reading 'substring') ```

The filter seem to be doing fine until the third letter is typped (ide) -indeed, it shows entrances that correspond to the entered terms-. However, entering the fourth letter triggers the error.

I am using the desktop app in Linux (Pop OS! 21.04) with a Vault created in Google Drive to be able to synchronize passwords among all my devices (Android Phone and Firefox).

I include the complete trace of the error in case it may be useful. Please, do not hesitate to ask me for any relevant test that may help determine the cause of the issue.

Thanks in advance for your help and attention.

```
Error
A fatal error has occurred - we're sorry this has happened. Please check out the details below in case they help diagnose the issue:

TypeError: Cannot read properties of undefined (reading 'substring')
    at Dn (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:274:20)
    at div
    at t (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:2:1194832)
    at t (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:2:1195319)
    at div
    at E (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:525:1490519)
    at div
    at E (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:525:1490519)
    at Wn (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:331:2406)
    at div
    at s (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:2:1146872)
    at div
    at t (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:2:1148353)
    at div
    at s (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:2:1146872)
    at div
    at t (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:2:1148353)
    at div
    at E (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:525:1490519)
    at Ba
    at De (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:215:6335)
    at Ne (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:525:1488607)
    at t.VaultEditor (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:628:51)
    at h (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:588:45)
    at div
    at E (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:525:1490519)
    at t.SearchProvider (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:697:2594)
    at div
    at E (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:525:1490519)
    at t.VaultManagement (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:638:64)
    at t (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:525:1384476)
    at t (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:525:1386434)
    at t (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:525:1381054)
    at t (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:525:1388339)
    at div
    at E (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:525:1490519)
    at Ne (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:525:1488607)
    at t.App (file:///tmp/.mount_ButterQzFiPm/resources/app.asar/build/renderer/index.js:530:42)
```

**Comment by samuelandert** [comment]
I am experiencing the same behaviour, when searching through imported passwords. It's kind of random, when this error gets triggered. Sometimes its already on the second letter, sometimes on the 8th or 10th. At least if you search the same terms, you can reproduce the same error trigger at the exact same letter.
