### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by victorffrock** [buttercup/buttercup-desktop#1217]
A fatal error has occurred - we're sorry this has happened. Please check out the details below in case they help diagnose the issue:

TypeError: undefined does not have a method named "toLowerCase"
    at kr (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:459:2382)
    at div
    at s (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:2:1261915)
    at div
    at t (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:2:1263396)
    at div
    at s (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:2:1261915)
    at div
    at t (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:2:1263396)
    at div
    at E (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:654:855822)
    at Gi
    at ct (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:339:5661)
    at Ce (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:654:853911)
    at t.VaultEditor (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:750:51)
    at h (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:717:45)
    at div
    at E (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:654:855822)
    at t.SearchProvider (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:827:5122)
    at div
    at E (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:654:855822)
    at t.VaultManagement (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:761:64)
    at t (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:654:758147)
    at t (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:654:760150)
    at t (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:654:753263)
    at t (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:654:763944)
    at div
    at E (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:654:855822)
    at file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:912:1374001
    at Ce (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:654:853911)
    at Ce (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:654:853911)
    at t.App (file:///tmp/.mount_ButterGp4KUB/resources/app.asar/build/renderer/index.js:659:42)

**Comment by garlos** [comment]
i have the same issue after updating buttercup to version 2.20.2

**Comment by victorffrock** [comment]
Exactly, it was after the update. I can no longer use the program.

**Comment by twhitman** [comment]
I have the same issue, though only when I try to access a particular group:

<img width="1475" alt="Screen Shot 2023-05-25 at 10 01 45 AM" src="https://github.com/buttercup/buttercup-desktop/assets/740739/47589129-a505-40f7-95f9-c2433ecb0400">

The issue began after updating to 2.20.2

**Comment by victorffrock** [comment]
I can't solve this problem. I cannot completely remove this program from my computer and reinstall. I don't have access to my passwords from the computer. Does anyone have a tip that might help me?

**Comment by perry-mitchell** [comment]
This issue has been mentioned elsewhere but I'm still unable to reproduce it.

Can someone either post steps to reproduce, if more complicated than just opening the app, or clone the repository and try to reproduce in development so we can get a better stack trace?

Unfortunate the stack provided isn't helpful.

**Comment by LambertPhil** [comment]
I've exactly the same issue but it is only when I click on 1 folder. If I go in the others, all work well. 

It is not in the data because if I export them in a CSV file and re import them in a new vault in the same folder (Import Laspass CSV), all is ok. If I import in a structured vault (Buttercup CSV) I get the same issue.

**Comment by TomasVojacek** [comment]
I was able reproduce issue,
with name of entry is empty see:
entry,bd2e398d-05a8-4e3f-bf61-69b91e2eb05a,,,,,,,2a61ed5d-8794-47a8-bb14-cb7890d0bd29,  
example.csv
[fault_vault.log](https://github.com/buttercup/buttercup-desktop/files/11627682/fault_vault.log)

**Comment by perry-mitchell** [comment]
Thanks for the details. They should be useful in reproducing.

**Comment by perry-mitchell** [comment]
If anyone is able to reproduce this with an empty/test vault, please consider sharing it here so I can test with it.

**Comment by perry-mitchell** [comment]
Ok, reproduced using the Buttercup CSV importer, my mistake:

![image](https://github.com/buttercup/buttercup-desktop/assets/3869469/0ffb799c-c086-40e6-98f4-6446dbf64db7)

It of course does not show itself via the standard CSV importer.

**Comment by perry-mitchell** [comment]
Ok, think I got it solved: 
![image](https://github.com/buttercup/buttercup-desktop/assets/3869469/47fe44af-5841-416e-8638-6e82c78b81ac)

**Comment by perry-mitchell** [comment]
Released: https://github.com/buttercup/buttercup-desktop/releases/tag/v2.20.3

**Comment by LambertPhil** [comment]
Hello, I confirm that it's work now. 

Thank you
