### ISSUE TITLE
Got an error when trying to set a filter with "abc"

### ISSUE THREAD

**Issue by vkcorp** [buttercup/buttercup-desktop#1261]
To search with a filter, I tried to typed "abc",
and I got an error message when I try to set it, with below message.

```
Error
A fatal error has occurred - we're sorry this has happened. Please check out the details below in case they help diagnose the issue:

TypeError: Cannot read properties of undefined (reading 'substring')
    at Jn (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:400:20)
    at div
    at t (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:2:1256520)
    at t (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:2:1256975)
    at div
    at w (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:654:847698)
    at div
    at w (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:654:847698)
    at dr (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:459:2382)
    at div
    at s (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:2:1261307)
    at div
    at t (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:2:1262788)
    at div
    at s (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:2:1261307)
    at div
    at t (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:2:1262788)
    at div
    at w (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:654:847698)
    at Pi
    at ct (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:339:5661)
    at Rt (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:654:845758)
    at t.VaultEditor (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:755:51)
    at h (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:717:45)
    at div
    at w (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:654:847698)
    at t.SearchProvider (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:832:5141)
    at div
    at w (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:654:847698)
    at t.VaultManagement (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:766:64)
    at t (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:654:751673)
    at t (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:654:753676)
    at t (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:654:746789)
    at t (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:654:757470)
    at div
    at w (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:654:847698)
    at file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:925:1369405
    at Rt (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:654:845758)
    at Rt (file:///C:/Users/jungh/AppData/Local/Programs/Buttercup/resources/app.asar/build/renderer/index.js:654:845758)
    at t.App (file:///C:/Users/jungh/AppData/Local
```

When I typed a last letter 'c', it's happened.

**Comment by perry-mitchell** [comment]
I can't reproduce.. Are you able to create a new vault and test if it still happens?

![image](https://github.com/buttercup/buttercup-desktop/assets/3869469/3913b82a-6630-4e4b-9cf5-cb0a2d02acdf)

**Comment by vkcorp** [comment]
Probably it's happened at one of my spcific group.
With new one, no problem.


![image](https://github.com/buttercup/buttercup-desktop/assets/6039321/f3322407-9995-41e5-99f0-8114c949d8f7)

**Comment by vkcorp** [comment]
Well, I guess I found item(s) which made this trouble.

If there is a item which doesn't have Username and Password but it have a custom field,
or No Username and have a Password,
it makes this trouble.

With devtools, I tried to find one by one which made error screen,
and fixed those items then providing 'n/a' as a value and no more problem now...

Well, there was only key or id (as UUID) and no title, so it's not easy to find what item makes it.

**Comment by vkcorp** [comment]
Actually I imported that group from JSON file, 
and I guess some items were out of rules but didn't filtered.
But I think I wouldn't set a item that doesn't have Username if needed...

**Comment by vkcorp** [comment]
Well, I tried to make new item which doesn't have Username and Password but have Custom fileld,
but it didn't make a trouble..
What a strange....
