### ISSUE TITLE
can not remove on unlock one of dropbox archives on mac

### ISSUE THREAD

**Issue by benyaminsalimi** [buttercup/buttercup-desktop#474]
it's happened on one of my archives, and I can not unlock it too
here is the error in unlocking : 
`Unhandled Error
TypeError: Cannot read property 'workspace' of undefined
    at u (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:6:35349)
    at Object.s [as f] (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:44:3636)
    at C (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:235:3393)
    at file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:68:183481
    at e (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:68:183035)
    at S (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:68:340025)
    at file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:68:183481
    at e (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:68:183035)
    at A (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:68:340260)
    at file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:68:183481`

and here is the error for removing:
`Unhandled Promise Rejection
VError: Failed removing sources: Source not found for ID
    at file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:1:823774
    at <anonymous>`
log file is attached too

**Comment by perry-mitchell** [comment]
I can confirm that I get this issue as well:

![image](https://user-images.githubusercontent.com/3869469/35873261-df7e5536-0b71-11e8-9cbb-ae5eb123836e.png)

```
Unhandled Promise Rejection
VError: Failed removing sources: Source not found for ID
    at file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:6:766235
    at <anonymous>
```
