### ISSUE TITLE
SOLVED - 1.0.1 issues error on launch and doesn't open archive anymore…

### ISSUE THREAD

**Issue by fmommeja** [buttercup/buttercup-desktop#501]
Here are the errors on Mac OSX 10.9.5:

Unhandled Error
TypeError: Cannot read property 'primary' of undefined
    at c (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:6:953139)
    at Object.s [as f] (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:44:3636)
    at O (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:249:2156)
    at file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:68:195990
    at e (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:68:195544)
    at S (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:44:7216)
    at file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:68:195990
    at e (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:68:195544)
    at A (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:44:7632)
    at file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:68:195990

Hope you can fix that soon…

Fred

**Comment by fmommeja** [comment]
That was just happening after the automatic update…
Quitting and relauching Buttercup solved the issue.

Thanks

Fred
