### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by farskid** [buttercup/buttercup-desktop#509]
Thanks for the great job on buttercup 👍 
I just installed desktop version using `brew cask` and creates a new archive.
Once entered the app after the archive step, I got this unhandled promise rejection alert.

Might also worth noting that I pushed the **check for updates** option too.

See attached image for more details:
<img width="947" alt="buttercup_error" src="https://user-images.githubusercontent.com/8332043/36058142-d055bfbc-0e2e-11e8-8895-9a92760ed2fe.png">

This is the whole error stack as well, hope it helps:

```js
Unhandled Promise Rejection
Error: The folder “app.zip” doesn’t exist.: The folder doesn’t exist.
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:71319:19)
    at new PromiseSpawn (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:73289:17)
    at /Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:73443:21
    at MacUpdater._checkForUpdates (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:8884:11)
    at MacUpdater.checkForUpdates (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:8830:39)
    at checkForUpdates (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:31842:67)
    at click (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:31480:84)
```

**Comment by sallar** [comment]
Thanks @farskid Closing this in favor of #517. Will try to focus on this next and find a solution.
