### ISSUE TITLE
Check for updates throws error, app does not update

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#517]
![image](https://user-images.githubusercontent.com/3869469/36205879-10ef2d2a-1199-11e8-87c1-011c6996e124.png)

This appeared after opening Bcup, as well as when clicking the "Check for updates" button. The update message in the bottom right also appeared (for 1.1.0), and after clicking that, it closes and opens again, but the version is still wrong:

![image](https://user-images.githubusercontent.com/3869469/36206102-d08a6424-1199-11e8-9634-def10ba7ee17.png)

![image](https://user-images.githubusercontent.com/3869469/36206114-d98fdd7e-1199-11e8-8a0d-66b9d5dcceb9.png)

After doing this 3 times, it updated to the correct version:

![image](https://user-images.githubusercontent.com/3869469/36206143-f3626fc8-1199-11e8-946a-fbb9e1e5ae41.png)

The log:

```
[2018-02-14 12:56:29:0834] [info] Checking for update
[2018-02-14 12:56:31:0254] [info] Found version 1.1.0 (url: buttercup-desktop-1.1.0-mac.zip, Buttercup-1.1.0.dmg)
[2018-02-14 12:56:31:0256] [info] Downloading update from buttercup-desktop-1.1.0-mac.zip, Buttercup-1.1.0.dmg
[2018-02-14 12:56:31:0392] [info] / requested
[2018-02-14 12:56:31:0401] [info] /app.zip requested
[2018-02-14 12:56:31:0718] [info] download-progress listener count: 0
[2018-02-14 12:56:44:0397] [info] New version 1.1.0 has been downloaded
[2018-02-14 12:57:41:0838] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/buttercup/buttercup-desktop/releases/download/v1.1.0/buttercup-desktop-1.1.0-mac.zip)
[2018-02-14 13:11:29:0823] [info] Checking for update
[2018-02-14 13:11:32:0626] [info] Found version 1.1.0 (url: buttercup-desktop-1.1.0-mac.zip, Buttercup-1.1.0.dmg)
[2018-02-14 13:11:32:0629] [info] Downloading update from buttercup-desktop-1.1.0-mac.zip, Buttercup-1.1.0.dmg
[2018-02-14 13:11:32:0799] [info] / requested
[2018-02-14 13:11:32:0808] [info] /app.zip requested
[2018-02-14 13:11:33:0123] [info] download-progress listener count: 0
[2018-02-14 13:11:45:0587] [info] New version 1.1.0 has been downloaded
[2018-02-14 13:12:34:0344] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/buttercup/buttercup-desktop/releases/download/v1.1.0/buttercup-desktop-1.1.0-mac.zip)
[2018-02-14 13:26:29:0808] [info] Checking for update
[2018-02-14 13:26:31:0194] [info] Found version 1.1.0 (url: buttercup-desktop-1.1.0-mac.zip, Buttercup-1.1.0.dmg)
[2018-02-14 13:26:31:0196] [info] Downloading update from buttercup-desktop-1.1.0-mac.zip, Buttercup-1.1.0.dmg
[2018-02-14 13:26:31:0333] [info] / requested
[2018-02-14 13:26:31:0341] [info] /app.zip requested
[2018-02-14 13:26:31:0649] [info] download-progress listener count: 0
[2018-02-14 15:08:09:0044] [warn] Error: The request timed out.
    at Object.showMessageBox (/Applications/Buttercup.app/Contents/Resources/electron.asar/browser/api/dialog.js:277:20)
    at handleError (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:106187:29)
    at process.on.err (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:106218:4)
    at emitOne (events.js:101:20)
    at process.emit (events.js:191:7)
    at process.emit (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:90763:21)
    at process._fatalException (bootstrap_node.js:308:26)

[2018-02-14 15:08:09:0047] [error] Error: Error: The request timed out.
    at Object.showMessageBox (/Applications/Buttercup.app/Contents/Resources/electron.asar/browser/api/dialog.js:277:20)
    at handleError (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:106187:29)
    at process.on.err (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:106218:4)
    at emitOne (events.js:101:20)
    at process.emit (events.js:191:7)
    at process.emit (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:90763:21)
    at process._fatalException (bootstrap_node.js:308:26)
[2018-02-14 15:08:13:0460] [error] Error: Error: The request timed out.
    at Object.showMessageBox (/Applications/Buttercup.app/Contents/Resources/electron.asar/browser/api/dialog.js:277:20)
    at handleError (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:106187:29)
    at process.on.err (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:106218:4)
    at emitOne (events.js:101:20)
    at process.emit (events.js:191:7)
    at process.emit (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:90763:21)
    at process._fatalException (bootstrap_node.js:308:26)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:71787:19)
    at new PromiseSpawn (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:73757:17)
    at /Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:73911:21
    at MacUpdater._checkForUpdates (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:8890:11)
    at MacUpdater.checkForUpdates (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:8836:39)
    at Timeout.checkForUpdates [as _onTimeout] (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:31853:67)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2018-02-14 15:08:25:0407] [info] Operation queue is not empty, waiting before quitting.
[2018-02-14 15:08:31:0106] [info] Buttercup starting up...
[2018-02-14 15:08:31:0290] [info] Restoring state... { settingsByArchiveId: { '2c7da6c4-fc5f-4b15-90c5-5cd196171d02': { ui: [Object] } },
  currentArchive: null,
  archives:
   [ { id: '2c7da6c4-fc5f-4b15-90c5-5cd196171d02',
       name: 'perry.bcup',
       status: 'locked',
       type: 'ipc',
       color: '#008b02' },
     { id: 'c159623a-b5f9-45a2-ab6e-e0036c2d93d3',
       name: 'auth.bcup',
       status: 'locked',
       type: 'ipc',
       color: '#d4c4fb' },
     { id: '484a1b16-e7c5-4ec4-ad12-49dc7c2b6907',
       name: 'sample.bcup',
       status: 'locked',
       type: 'ipc' } ],
  update: { available: false, version: null, notes: null },
  settings:
   { columnSizes: { tree: 230, entries: 235 },
     condencedSidebar: true,
     locale: 'en' } }
[2018-02-14 15:08:31:0405] [info] Checking for update
[2018-02-14 15:08:33:0191] [info] Found version 1.1.0 (url: buttercup-desktop-1.1.0-mac.zip, Buttercup-1.1.0.dmg)
[2018-02-14 15:08:33:0193] [info] Downloading update from buttercup-desktop-1.1.0-mac.zip, Buttercup-1.1.0.dmg
[2018-02-14 15:08:33:0236] [info] / requested
[2018-02-14 15:08:33:0242] [info] /app.zip requested
[2018-02-14 15:08:33:0581] [info] download-progress listener count: 0
[2018-02-14 15:08:42:0508] [info] Checking for update
[2018-02-14 15:08:43:0329] [info] Found version 1.1.0 (url: buttercup-desktop-1.1.0-mac.zip, Buttercup-1.1.0.dmg)
[2018-02-14 15:08:43:0330] [info] Downloading update from buttercup-desktop-1.1.0-mac.zip, Buttercup-1.1.0.dmg
[2018-02-14 15:08:43:0350] [info] / requested
[2018-02-14 15:08:43:0353] [info] /app.zip requested
[2018-02-14 15:08:43:0653] [info] download-progress listener count: 0
[2018-02-14 15:08:43:0797] [warn] Error: ditto: /Users/perry/Library/Caches/pw.buttercup.desktop.ShipIt/update.7OalJSl/Buttercup.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib: No such file or directory

[2018-02-14 15:08:43:0797] [error] Error: Error: ditto: /Users/perry/Library/Caches/pw.buttercup.desktop.ShipIt/update.7OalJSl/Buttercup.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib: No such file or directory
[2018-02-14 15:08:43:0800] [error] Error: Error: ditto: /Users/perry/Library/Caches/pw.buttercup.desktop.ShipIt/update.7OalJSl/Buttercup.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib: No such file or directory
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:71787:19)
    at new PromiseSpawn (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:73757:17)
    at /Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:73911:21
    at MacUpdater._checkForUpdates (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:8890:11)
    at MacUpdater.checkForUpdates (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:8836:39)
    at checkForUpdates (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:31853:67)
    at click (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:31491:84)
    at MenuItem.click (/Applications/Buttercup.app/Contents/Resources/electron.asar/browser/api/menu-item.js:52:9)
    at Function.executeCommand (/Applications/Buttercup.app/Contents/Resources/electron.asar/browser/api/menu.js:121:15)
[2018-02-14 15:09:35:0919] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/buttercup/buttercup-desktop/releases/download/v1.1.0/buttercup-desktop-1.1.0-mac.zip)
[2018-02-14 15:09:38:0639] [info] Checking for update
[2018-02-14 15:09:39:0311] [info] New version 1.1.0 has been downloaded
[2018-02-14 15:09:40:0332] [info] Found version 1.1.0 (url: buttercup-desktop-1.1.0-mac.zip, Buttercup-1.1.0.dmg)
[2018-02-14 15:09:40:0334] [info] Downloading update from buttercup-desktop-1.1.0-mac.zip, Buttercup-1.1.0.dmg
[2018-02-14 15:09:40:0408] [info] / requested
[2018-02-14 15:09:40:0412] [info] /app.zip requested
[2018-02-14 15:09:40:0713] [info] download-progress listener count: 0
[2018-02-14 15:09:43:0686] [info] Operation queue is not empty, waiting before quitting.
[2018-02-14 15:09:49:0369] [info] Buttercup starting up...
[2018-02-14 15:09:49:0566] [info] Restoring state... { settingsByArchiveId: { '2c7da6c4-fc5f-4b15-90c5-5cd196171d02': { ui: [Object] } },
  currentArchive: null,
  archives:
   [ { id: '2c7da6c4-fc5f-4b15-90c5-5cd196171d02',
       name: 'perry.bcup',
       status: 'locked',
       type: 'ipc',
       color: '#008b02' },
     { id: 'c159623a-b5f9-45a2-ab6e-e0036c2d93d3',
       name: 'auth.bcup',
       status: 'locked',
       type: 'ipc',
       color: '#d4c4fb' },
     { id: '484a1b16-e7c5-4ec4-ad12-49dc7c2b6907',
       name: 'sample.bcup',
       status: 'locked',
       type: 'ipc' } ],
  update: { available: false, version: null, notes: null },
  settings:
   { columnSizes: { tree: 230, entries: 235 },
     condencedSidebar: true,
     locale: 'en' } }
[2018-02-14 15:09:49:0683] [info] Checking for update
[2018-02-14 15:09:51:0308] [info] Found version 1.1.0 (url: buttercup-desktop-1.1.0-mac.zip, Buttercup-1.1.0.dmg)
[2018-02-14 15:09:51:0310] [info] Downloading update from buttercup-desktop-1.1.0-mac.zip, Buttercup-1.1.0.dmg
[2018-02-14 15:09:51:0356] [info] / requested
[2018-02-14 15:09:51:0361] [info] /app.zip requested
[2018-02-14 15:09:51:0694] [info] download-progress listener count: 0
[2018-02-14 15:10:02:0332] [info] New version 1.1.0 has been downloaded
[2018-02-14 15:10:52:0335] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/buttercup/buttercup-desktop/releases/download/v1.1.0/buttercup-desktop-1.1.0-mac.zip)
[2018-02-14 15:15:20:0612] [info] Operation queue is not empty, waiting before quitting.
[2018-02-14 15:15:23:0132] [info] Buttercup starting up...
[2018-02-14 15:15:23:0375] [info] Restoring state... { settingsByArchiveId: { '2c7da6c4-fc5f-4b15-90c5-5cd196171d02': { ui: [Object] } },
  currentArchive: null,
  archives:
   [ { id: '2c7da6c4-fc5f-4b15-90c5-5cd196171d02',
       name: 'perry.bcup',
       status: 'locked',
       type: 'ipc',
       color: '#008b02' },
     { id: 'c159623a-b5f9-45a2-ab6e-e0036c2d93d3',
       name: 'auth.bcup',
       status: 'locked',
       type: 'ipc',
       color: '#d4c4fb' },
     { id: '484a1b16-e7c5-4ec4-ad12-49dc7c2b6907',
       name: 'sample.bcup',
       status: 'locked',
       type: 'ipc' } ],
  update: { available: false, version: null, notes: null },
  settings:
   { columnSizes: { tree: 230, entries: 235 },
     condencedSidebar: true,
     locale: 'en' } }
[2018-02-14 15:15:23:0538] [info] Checking for update
[2018-02-14 15:15:25:0331] [info] Update for version 1.1.0 is not available (latest version: 1.1.0, downgrade is disallowed.
```

**Comment by sallar** [comment]
@perry-mitchell what is ditto? :D

**Comment by perry-mitchell** [comment]
@sallar Good question! But it's throwing an error in Buttercup 😅

**Comment by sallar** [comment]
@perry-mitchell Telegram is using Squirrel for macOS and electron is using the same but electron cant have the nice GUI in native mac apps :( I'll look into finding another solution for updates. We're currently using this which makes it possible to update Linux and Windows in addition to macOS, also supports Github releases which we are using: https://www.electron.build/auto-update

But maybe the version that we're using is old and unstable. I'll look into it. But I like your suggestion about a new flow. Maybe we shouldn't be updating automatically right?

**Comment by perry-mitchell** [comment]
Well it’s tricky. Right now the auto update doesn’t work at all for Linux, so it’s only Mac and Windows. I do like the auto update functionality.. we could just implement it ourselves even:

1. Check for update
2. Prompt user
3. Download .exe/.dmg/.deb
4. Execute file

Obviously Mac is more complicated because we need to overwrite an app file. Windows and Linux could probably just install over the top?

We could also use a 3rd party installer and updated for our app instead of the electron one.. we don’t necessarily need it integrated. Maybe we need to ponder on this a bit 🧐

**Comment by sallar** [comment]
@perry-mitchell I suggest we find a tested and ready-made solution or fix the current one (maybe it's my implementation that is broken and not the solution itself) instead of investing in time implementing it yourself. I haven't seen any electron apps to do this on their own. The update functionality is built into electron core itself: https://github.com/electron/electron/blob/master/docs/api/auto-updater.md
The package im using is just a high level wrapper.

I think these errors are happening because im not handling errors and recovering from them correctly.

**Comment by perry-mitchell** [comment]
Agreed. Errors or not, I personally feel that the auto update functionality is a bit risky - downloading 50-60 mb in the background is tricky and uses a bit of data. Would be good to have the ability to postpone it to next launch..

**Comment by sallar** [comment]
@perry-mitchell Well I fully agree with changing the flow. At least we should give the user the possibility to opt-in to downloading automatically. Plus, while it's downloading, we should show a progress indicator and also catch the errors nicely.

**Comment by fmommeja** [comment]
Worked perfectly now for me!

Thanks a lot.
Kind regards

Frederic
