### ISSUE TITLE
Check for updates throws error, app does not update to 1.3.0

### ISSUE THREAD

**Issue by fmommeja** [buttercup/buttercup-desktop#547]
New issue today on Mac (with 1.3.0 update):

`Unhandled Promise Rejection Error: La requête a expiré. at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:71191:19) at new PromiseSpawn (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:73161:17) at /Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:73315:21 at MacUpdater._checkForUpdates (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:8335:11) at MacUpdater.checkForUpdates (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:8281:39) at Timeout.checkForUpdates [as _onTimeout] (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:31898:67)`

After this message, no more update is found and Buttercup remains in 1.2.2…

Here is the log:
[20180222log.log](https://github.com/buttercup/buttercup-desktop/files/1749863/20180222log.log)

Kind regards

-- 
Frederic

**Comment by fmommeja** [comment]
New try… here is the associated log:
`[2018-02-22 23:54:46:0638] [info] Checking for update
[2018-02-22 23:54:48:0121] [info] Found version 1.3.0 (url: buttercup-desktop-1.3.0-mac.zip, Buttercup-1.3.0.dmg)
[2018-02-22 23:54:48:0122] [info] Downloading update from buttercup-desktop-1.3.0-mac.zip, Buttercup-1.3.0.dmg
[2018-02-22 23:54:48:0187] [info] / requested
[2018-02-22 23:54:48:0193] [info] /app.zip requested
[2018-02-22 23:54:48:0501] [info] download-progress listener count: 0
[2018-02-22 23:55:55:0515] [info] New version 1.3.0 has been downloaded
[2018-02-22 23:56:28:0196] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/buttercup/buttercup-desktop/releases/download/v1.3.0/buttercup-desktop-1.3.0-mac.zip)
[2018-02-23 00:09:46:0731] [info] Checking for update
[2018-02-23 00:09:48:0034] [info] Found version 1.3.0 (url: buttercup-desktop-1.3.0-mac.zip, Buttercup-1.3.0.dmg)
[2018-02-23 00:09:48:0035] [info] Downloading update from buttercup-desktop-1.3.0-mac.zip, Buttercup-1.3.0.dmg
[2018-02-23 00:09:48:0117] [info] / requested
[2018-02-23 00:09:48:0122] [info] /app.zip requested
[2018-02-23 00:09:48:0417] [info] download-progress listener count: 0
[2018-02-23 00:09:53:0374] [info] Operation queue is not empty, waiting before quitting.
[2018-02-23 00:09:59:0420] [info] Buttercup starting up...
[2018-02-23 00:09:59:0664] [info] Restoring state... { settingsByArchiveId: { '1c0c6638-c44c-4641-b761-30d0e5130d1d': { ui: [Object] } },
  currentArchive: null,
  archives: 
   [ { name: 'FLEM.bcup',
       id: '1c0c6638-c44c-4641-b761-30d0e5130d1d',
       status: 'locked',
       type: 'ipc',
       colour: '#000000',
       order: 0 } ],
  update: { available: false, version: null, notes: null },
  settings: 
   { columnSizes: { tree: 230, entries: 230 },
     condencedSidebar: true,
     menubarVisible: true,
     locale: 'fr',
     archivesLoading: false } }
[2018-02-23 00:09:59:0785] [info] Checking for update
[2018-02-23 00:10:01:0395] [info] Found version 1.3.0 (url: buttercup-desktop-1.3.0-mac.zip, Buttercup-1.3.0.dmg)
[2018-02-23 00:10:01:0397] [info] Downloading update from buttercup-desktop-1.3.0-mac.zip, Buttercup-1.3.0.dmg
[2018-02-23 00:10:01:0423] [info] / requested
[2018-02-23 00:10:01:0428] [info] /app.zip requested
[2018-02-23 00:10:01:0787] [info] download-progress listener count: 0
`

**Comment by sallar** [comment]
@fmommeja this issue is fixed in 1.3, so you'll need to probably manually install 1.3 if the update doesn't work
