### ISSUE TITLE
1.7.0 fails to build

### ISSUE THREAD

**Issue by sum01** [buttercup/buttercup-desktop#612]
1.7.0 fails to build from source on Arch Linux. Seems node-sass is the cause?

`makepkg -L` Build.log
```
make: *** [binding.target.mk:115: Release/obj.target/binding/src/binding.o] Error 1
make: *** [binding.target.mk:115: Release/obj.target/binding/src/sass_types/color.o] Error 1
make: *** [binding.target.mk:115: Release/obj.target/binding/src/custom_importer_bridge.o] Error 1
make: *** [binding.target.mk:115: Release/obj.target/binding/src/sass_context_wrapper.o] Error 1
make: Leaving directory 'buttercup-desktop/src/buttercup-desktop-1.7.0/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (buttercup-desktop/src/buttercup-desktop-1.7.0/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Linux 4.16.9-1-ARCH
gyp ERR! command "/usr/bin/node" "buttercup-desktop/src/buttercup-desktop-1.7.0/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd buttercup-desktop/src/buttercup-desktop-1.7.0/node_modules/node-sass
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.2.0 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-mac@1.8.3 (node_modules/app-builder-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-mac@1.8.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-win@1.8.3 (node_modules/app-builder-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-win@1.8.3: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@0.3.10 (node_modules/appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.3.10: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.0.17 (node_modules/kdbxweb/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-mac@1.7.2 (node_modules/dmg-builder/node_modules/app-builder-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-mac@1.7.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-win@1.7.2 (node_modules/dmg-builder/node_modules/app-builder-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-win@1.7.2: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     buttercup-desktop/src/npm-cache/_logs/2018-05-21T16_31_02_834Z-debug.log
[1m[31m==> ERROR:(B[m[1m A failure occurred in build().(B[m
[1m    Aborting...(B[m
```

The referenced debug.log (warning, very big) https://gist.github.com/sum01/e185ab2e626404a7c90ba81b581a0d4c

**Comment by sallar** [comment]
@sum01 I think I messed up and forgot to merge a branch :( Can you try master again?

**Comment by sallar** [comment]
That's new from npm @sum01, I fixed most of the issues, I'll fix the rest soon. Some packages haven't released any updates

**Comment by sum01** [comment]
Is a new tag going to be pushed soon, or should I create a patch using your untagged commits for the AUR?

**Comment by sallar** [comment]
@sum01 I did tag it again. Can you check if it works?

**Comment by sum01** [comment]
@sallar Indeed it built, thanks for tagging.
