### ISSUE TITLE
[Linux] Checking for updates fails

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#641]
Updates are not notified on desktop on ubuntu (18). The following error occurs:

```
[09:37:29:0928] [info] Checking for update
[09:37:29:0957] [error] Error: Error: ENOENT: no such file or directory, open '/opt/Buttercup/resources/app-update.yml'
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/opt/Buttercup/resources/app.asar/dist/app.js:70742:19)
    at new PromiseSpawn (/opt/Buttercup/resources/app.asar/dist/app.js:72712:17)
    at /opt/Buttercup/resources/app.asar/dist/app.js:72866:21
    at AppImageUpdater._checkForUpdates (/opt/Buttercup/resources/app.asar/dist/app.js:8181:11)
    at AppImageUpdater.checkForUpdates (/opt/Buttercup/resources/app.asar/dist/app.js:8127:39)
    at checkForUpdates (/opt/Buttercup/resources/app.asar/dist/app.js:7866:67)
    at Timeout.setTimeout (/opt/Buttercup/resources/app.asar/dist/app.js:105399:101)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

Version is currently 1.8.

**Comment by perry-mitchell** [comment]
@sallar Any idea what might be happening here? Not sure why the file is downloaded to disk.. Would think that it could/should just go to memory?

**Comment by ShinIce** [comment]
Hi there :)
Any info about this issue?

**Comment by svenvdvoort** [comment]
Hello,
I would just like to say that issue is still occurring on Ubuntu LTS 18.04, with the latest .deb downloaded from the website.
My logs are the same as in the message above. When I take a look in the folder '/opt/Buttercup/resources' there is no file name 'app-update.yml'. Only the files 'app.asar', 'default_app.asar' and 'electron.asar' are in that folder.
Cheers,
Sven.

**Comment by eldy** [comment]
I have same issue. Version 1.8.1

**Comment by IamNaN** [comment]
Just installed Buttercup and this was the first thing I saw. I'm using Mint/Cinnamon/Tina. I've just been living with it the past two weeks since I first installed it. This is over a year old... is Buttercup still in development?

**Comment by perry-mitchell** [comment]
> is Buttercup still in development

Constantly :)

**Comment by perry-mitchell** [comment]
Should be fixed in v2.
