### ISSUE TITLE
New entries to WebDAV archive not saving on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by sanelkukic** [buttercup/buttercup-desktop#726]
So recently I added an entry to a group in my archive called General.

I entered the username and chose to generate a random password using the built-in generator in Buttercup. All is good, I click save.

Then I right click the archive and click Lock, and I close the app window.

However, when I attempt to re-open the archive on either mobile or desktop, the entry I just added is no longer there, as if I never even added it.

What's going on?

Some helpful info:
Desktop specs: Ubuntu 18.04 LTS, Linux kernel v4.19.11, unknown Buttercup version (how do I check the Buttercup version again?)
Mobile specs: Android 6.0.1 Marshmallow, Buttercup mobile app version 1.5.0 from Play Store.
Archive is stored on my own WebDAV VPS server.

**Comment by xDrixxyz** [comment]
[Here's the log](https://ipfs.xdrixxyz.eu.org/ipfs/QmeMMZ6mxNWrJxdQzqkN5n2YpmQtsnnzEtcNDiuhdkjB2T/#EAiimDRnHKqEaxXdNZkJiCXEk3V4qbavmq7ixGPamcsm), and as for the about menu, I couldn't get it to open - clicking About didn't do anything, I think it's because of the missing file `/opt/Buttercup/resources/app-update.yaml` but I might be wrong.

**Comment by perry-mitchell** [comment]
I've attached the last lines of the log here for easier reading (end of log):

```
[2018-12-20 18:26:23:0788] [info] Running before-quit operation.
[2018-12-20 18:26:26:0046] [info] Buttercup starting up...
[2018-12-20 18:26:26:0172] [info] Restoring state... { settingsByArchiveId: { 'ff48cb02-1a6b-4e01-95e1-5104ea300e79': { ui: [Object] } },
  currentArchive: null,
  archives:
   [ { name: 'xpasswords.bcup',
       id: 'ff48cb02-1a6b-4e01-95e1-5104ea300e79',
       status: 'locked',
       type: 'webdav',
       colour: '#2c2f33',
       order: 0 } ],
  settings:
   { columnSizes: { tree: 230, entries: 230 },
     condencedSidebar: true,
     menubarAutoHide: false,
     archivesLoading: false,
     isTrayIconEnabled: true,
     isBrowserAccessEnabled: false,
     locale: 'en' } }
[2018-12-20 18:26:31:0977] [info] Checking for update
[2018-12-20 18:26:32:0009] [error] Error: Error: ENOENT: no such file or directory, open '/opt/Buttercup/resources/app-update.yml'
    at j.B [as _captureStackTrace] (/opt/Buttercup/resources/app.asar/dist/app.js:198:151655)
    at new d (/opt/Buttercup/resources/app.asar/dist/app.js:198:181335)
    at /opt/Buttercup/resources/app.asar/dist/app.js:198:184424
    at t.AppImageUpdater._checkForUpdates (/opt/Buttercup/resources/app.asar/dist/app.js:71:19408)
    at t.AppImageUpdater.checkForUpdates (/opt/Buttercup/resources/app.asar/dist/app.js:71:18244)
    at ac (/opt/Buttercup/resources/app.asar/dist/app.js:406:122886)
    at Timeout.setTimeout (/opt/Buttercup/resources/app.asar/dist/app.js:406:132374)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
[2018-12-20 19:37:44:0378] [info] Running before-quit operation.
```

@sallar I guess there's no log for saves currently?

**Comment by sallar** [comment]
@perry-mitchell this is interesting.. I guess not :(

**Comment by tmotyl** [comment]
same error here, fresh install from deb (v1.19) on ubuntu 19.10
