### ISSUE TITLE
Error on npm run start

### ISSUE THREAD

**Issue by SamuelNitsche** [buttercup/buttercup-desktop#747]
Hey, I wanted to add a feature to buttercup but every time I try to run it, I get the following error.

```
Unhandled Error
TypeError: buttercup_dist_buttercup_web_min__WEBPACK_IMPORTED_MODULE_0___default.a.vendor.webdav.setFetchMethod is not a function
    at eval (webpack-internal:///./src/renderer/index.js:53:87)
    at Module../src/renderer/index.js (http://localhost:3000/app/main.bundle.js:13001:1)
    at __webpack_require__ (http://localhost:3000/app/main.bundle.js:725:30)
    at fn (http://localhost:3000/app/main.bundle.js:102:20)
    at Object.0 (http://localhost:3000/app/main.bundle.js:14001:18)
    at __webpack_require__ (http://localhost:3000/app/main.bundle.js:725:30)
    at http://localhost:3000/app/main.bundle.js:792:37
    at http://localhost:3000/app/main.bundle.js:795:10
```

Am I missing something, maybe a dependency or something?

**Comment by ph1p** [comment]
Hi! I have also created an issue https://github.com/buttercup/buttercup-desktop/issues/740
Simple solution. Remove this Line: https://github.com/buttercup/buttercup-desktop/blob/master/src/renderer/index.js#L37

**Comment by SamuelNitsche** [comment]
Oh, did't see that one. Thank you very much!

**Comment by perry-mitchell** [comment]
We can leave this open for now - The fetch method is out of sync with core.

**Comment by perry-mitchell** [comment]
Stale
