### ISSUE TITLE
After the last update

### ISSUE THREAD

**Issue by regoremor** [buttercup/buttercup-desktop#786]
buttercup-desktop: v1.16.0
buttercup-database: Dropbox

The information can not be updated. When you save it shows the following error message.

Unhandled Promise Rejection
Error: Request failed with status code 400
    at e.exports (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:356:254552)
    at e.exports (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:369:1318)
    at XMLHttpRequest.h.(anonymous function) (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:356:253550)

I installed v1.15.0 and everything works fine again.

**Comment by alnacle** [comment]
Same issue here:

buttercup v1.16.0 (Dropbox)

Unhandled Promise Rejection
Error: Request failed with status code 400
    at e.exports (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:356:254552)
    at e.exports (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:369:1318)
    at XMLHttpRequest.h.(anonymous function) (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:356:253550)

**Comment by perry-mitchell** [comment]
Ok, seems I can reproduce this now.. I'll close in favour of #780 that is the same issue.
