### ISSUE TITLE
Something Crashed

### ISSUE THREAD

**Issue by Doracoin** [buttercup/buttercup-desktop#790]
Unhandled Error
TypeError: Cannot read property 'isInTrash' of null
    at file:///C:/Program%20Files/Buttercup/resources/app.asar/dist/main.bundle.js:607:3316
    at file:///C:/Program%20Files/Buttercup/resources/app.asar/dist/main.bundle.js:607:3329
    at file:///C:/Program%20Files/Buttercup/resources/app.asar/dist/main.bundle.js:156:173
    at Object.onRemoveClick (file:///C:/Program%20Files/Buttercup/resources/app.asar/dist/main.bundle.js:1:87682)
    at Zo.Xo [as handleRemoveClick] (file:///C:/Program%20Files/Buttercup/resources/app.asar/dist/main.bundle.js:607:940)
    at click (file:///C:/Program%20Files/Buttercup/resources/app.asar/dist/main.bundle.js:607:737)
    at CallbacksRegistry.apply (C:/Program Files/Buttercup/resources/electron.asar/common/api/callbacks-registry.js:47:25)
    at EventEmitter.ipcRenderer.on (C:/Program Files/Buttercup/resources/electron.asar/renderer/api/remote.js:285:21)

**Comment by sallar** [comment]
Thanks @Doracoin, could you please tell me how did you get to the point where this error occurred?

**Comment by perry-mitchell** [comment]
Stale
