### ISSUE TITLE
Error: New version X is not signed by the application owner

### ISSUE THREAD

**Issue by Jib-san** [buttercup/buttercup-desktop#826]
Hello,

I've tried to update (as admin or not) from 1.16.2 to 1.17.0 and got the error bellow.

Config: Windows 10 Pro 1903 build 18999.1

```
Unhandled Promise Rejection
Error: New version 1.17.0 is not signed by the application owner: publisherNames: COMODO RSA Code Signing CA, raw info: {
  "SignerCertificate": {
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=COMODO RSA Code Signing CA, O=COMODO CA Limited, L=Salford, S=Greater Manchester, C=GB",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1578009599000)/",
    "NotBefore": "/Date(1546387200000)/",
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "00BDC2D8815A5B41D6045C6C719D8A8F2A",
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.11",
      "FriendlyName": "sha256RSA"
    },
    "Thumbprint": "A9C56AD137B3A5359A375A1FA4827DDD071A845A",
    "Version": 3,
    "Issuer": "CN=COMODO RSA Code Signing CA, O=COMODO CA Limited, L=Salford, S=Greater Manchester, C=GB",
    "Subject": "CN=MadDev Oy, O=MadDev Oy, STREET=N�kinkaari 4 A, L=Espoo, S=Uusimaa, PostalCode=02320, C=FI"
  },
  "TimeStamperCertificate": {
    "Archived": false,
    "Extensions": [
      "System.Security.Cryptography.X509Certificates.X509KeyUsageExtension",
      "System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension",
      "System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509SubjectKeyIdentifierExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension"
    ],
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=DigiCert Assured ID CA-1, OU=www.digicert.com, O=DigiCert Inc, C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1729555200000)/",
    "NotBefore": "/Date(1413936000000)/",
    "HasPrivateKey": false,
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "03019A023AFF58B16BD6D5EAE617F066",
    "SubjectName": {
      "Name": "CN=DigiCert Timestamp Responder, O=DigiCert, C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.5",
      "FriendlyName": "sha1RSA"
    },
    "Thumbprint": "614D271D9102E30169822487FDE5DE00A352B01D",
    "Version": 3,
    "Handle": 2033362280896,
    "Issuer": "CN=DigiCert Assured ID CA-1, OU=www.digicert.com, O=DigiCert Inc, C=US",
    "Subject": "CN=DigiCert Timestamp Responder, O=DigiCert, C=US"
  },
  "Status": 0,
  "StatusMessage": "Signature v�rifi�e."
}
    at t.newError (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:1:8496)
    at Object.<anonymous> (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:207:228505)
    at Generator.next (<anonymous>)
    at Generator.c (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:1:1411)
    at d._promiseFulfilled (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:189112)
    at j._settlePromise (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:145545)
    at j._settlePromise0 (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:146143)
    at j._settlePromises (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:147495)
    at d (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:149218)
    at p (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:149157)
    at s._drainQueues (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:150677)
    at Immediate.drainQueues [as _onImmediate] (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:148899)
From previous event:
    at j.z [as _captureStackTrace] (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:164744)
    at new d (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:187987)
    at C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:191076
    at t.NsisUpdater.downloadUpdate (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:71:20764)
    at EventEmitter.i.ipcMain.on (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:414:129520)
    at WebContents.<anonymous> (C:/Program Files/Buttercup/resources/electron.asar/browser/api/web-contents.js:285:13)
```

**Comment by tertortoise** [comment]
Hi, the same issue on Win10.

**Comment by julianpoemp** [comment]
Can everyone please check to see if the issue is resolved? I deleted and re-uploaded a new version of signed windows files.

_Originally posted by @sallar in https://github.com/buttercup/buttercup-desktop/issues/805#issuecomment-544288377_

**Comment by Jib-san** [comment]
> Can everyone please check to see if the issue is resolved? I deleted and re-uploaded a new version of signed windows files.
> 
> _Originally posted by @sallar in [#805 (comment)](https://github.com/buttercup/buttercup-desktop/issues/805#issuecomment-544288377)_

**Comment by Jib-san** [comment]
It works now! 

Thanks @julianpoemp

**Comment by perry-mitchell** [comment]
This issue is present in 1.17.3 still:

```
Unhandled Promise Rejection
Error: New version 1.17.3 is not signed by the application owner: publisherNames: COMODO RSA Code Signing CA, raw info: {
  "SignerCertificate": {
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=COMODO RSA Code Signing CA, O=COMODO CA Limited, L=Salford, S=Greater Manchester, C=GB",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1578009599000)/",
    "NotBefore": "/Date(1546387200000)/",
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "00BDC2D8815A5B41D6045C6C719D8A8F2A",
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.11",
      "FriendlyName": "sha256RSA"
    },
    "Thumbprint": "A9C56AD137B3A5359A375A1FA4827DDD071A845A",
    "Version": 3,
    "Issuer": "CN=COMODO RSA Code Signing CA, O=COMODO CA Limited, L=Salford, S=Greater Manchester, C=GB",
    "Subject": "CN=MadDev Oy, O=MadDev Oy, STREET=-, L=-, S=-, PostalCode=-, C=FI"
  },
  "TimeStamperCertificate": {
    "Archived": false,
    "Extensions": [
      "System.Security.Cryptography.X509Certificates.X509KeyUsageExtension",
      "System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension",
      "System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509SubjectKeyIdentifierExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension"
    ],
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=DigiCert Assured ID CA-1, OU=www.digicert.com, O=DigiCert Inc, C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1729555200000)/",
    "NotBefore": "/Date(1413936000000)/",
    "HasPrivateKey": false,
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "03019A023AFF58B16BD6D5EAE617F066",
    "SubjectName": {
      "Name": "CN=DigiCert Timestamp Responder, O=DigiCert, C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.5",
      "FriendlyName": "sha1RSA"
    },
    "Thumbprint": "614D271D9102E30169822487FDE5DE00A352B01D",
    "Version": 3,
    "Handle": 1665920359584,
    "Issuer": "CN=DigiCert Assured ID CA-1, OU=www.digicert.com, O=DigiCert Inc, C=US",
    "Subject": "CN=DigiCert Timestamp Responder, O=DigiCert, C=US"
  },
  "Status": 0,
  "StatusMessage": "Signature verified."
}
    at t.newError (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:1:8496)
    at Object.<anonymous> (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:208:228422)
    at Generator.next (<anonymous>)
    at Generator.c (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:1:1486)
    at f._promiseFulfilled (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:207:349375)
    at D._settlePromise (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:207:305779)
    at D._settlePromise0 (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:207:306377)
    at D._settlePromises (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:207:307729)
    at f (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:207:309452)
    at p (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:207:309391)
    at s._drainQueues (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:207:310911)
    at Immediate.drainQueues [as _onImmediate] (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:207:309133)
From previous event:
    at D.R [as _captureStackTrace] (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:207:325005)
    at new f (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:207:348250)
    at C:/Program Files/Buttercup/resources/app.asar/dist/app.js:207:351339
    at t.NsisUpdater.downloadUpdate (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:71:20685)
    at EventEmitter.r.ipcMain.on (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:363:134457)
    at WebContents.<anonymous> (C:/Program Files/Buttercup/resources/electron.asar/browser/api/web-contents.js:285:13)
```

**Comment by perry-mitchell** [comment]
From https://github.com/buttercup/buttercup-desktop/issues/805#issuecomment-549265891:

> Probably it is the same issue as this one here. 
> https://github.com/electron-userland/electron-builder/issues/3667

> Have you tried setting the "publisherName" in package.json? This seemed to help in one case. Obviously it has to match with the subject CN from the signer certificate ("MadDev Oy").
> https://github.com/electron-userland/electron-builder/issues/3667#issuecomment-463227859

Which I believe @sallar tried already. May need more investigation.

**Comment by Jib-san** [comment]
Indeed, the error is still present for me too.

_Tested on Windows 10, latest Insider build._

**Comment by sallar** [comment]
Hi everyone. I have tried to upgrade electron and electron-updater to see if things improve or not. I have forked buttercup to my own personal account and release a few test versions for testing this issue. Would you mind uninstalling the current Buttercup on your Windows, and installing this version:
https://github.com/sallar/buttercup-desktop/releases/download/v1.21.0/Buttercup-Setup-1.21.0.exe
To see if it auto updates correctly to v1.22.0?
Please dont forget to uninstall it again after the test, as the versions are not correct for the official releases.

Thank you!

**Comment by ws141** [comment]
@sallar I've been having the same issue as described above and I just tested the version you linked above (1.21) which seems to update to (1.22) just fine! 👍
