### ISSUE TITLE
503 error while saving (was #817)

### ISSUE THREAD

**Issue by fmommeja** [buttercup/buttercup-desktop#833]
Still happening with 1.17.2 when trying to save and edited element:

`Unhandled Promise Rejection Error: Request failed with status code 503 at e.exports (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:361:269668) at e.exports (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:384:2582) at XMLHttpRequest.d.onreadystatechange (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:361:268605)`

Configuration : Buttercup Version 1.17.2 (1.17.2)
MacOS Sierra v. 10.12.6 (16G2136)

EDIT:
URL used while getting this error: `https://ncloud.zaclys.com/remote.php/webdav`

**Comment by westware** [comment]
Im also getting this exact error whenever I try to add anything (new group, new credential) or try to move a group or entry inside another group (didnt try also editing/deleting stuff)

I was also getting an error like this (if not the same) in previous versions 1.17 and 1.17.1

Buttercup 1.17.2 (1.17.2)
MacOs 10.14.6 (18G95)
archive on selfhosted Nextcloud 16.0.5

**Comment by Fl3eK** [comment]
Hi,

I had a similar error when adding an archive from Cloud, must try multiple times to get filemanager showing the content of my WebDAV share. When I finally succeeded to choose one, I've got a 503 when entering password of the archive ...

Here is the log from my console : 

```
/opt/Buttercup/resources/app.asar/dist/main.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
nextcloud.fl3ek.com/remote.php/webdav/%23security/home.bcup:1 Failed to load resource: the server responded with a status of 503 ()
main.bundle.js:361 GET https://XXXXXXXXX.com/remote.php/webdav/%23blablabla/archive.bcup 503 ()
(anonymous) @ main.bundle.js:361
e.exports @ main.bundle.js:361
e.exports @ main.bundle.js:384
_tickCallback @ internal/process/next_tick.js:68
Promise.then (async)
u.request @ main.bundle.js:384
(anonymous) @ main.bundle.js:361
i.patchInline.e @ main.bundle.js:384
(anonymous) @ main.bundle.js:384
execute @ main.bundle.js:361
patchInline @ main.bundle.js:361
s @ main.bundle.js:384
e.exports @ main.bundle.js:384
request @ main.bundle.js:361
getFileContentsString @ main.bundle.js:385
getFileContents @ main.bundle.js:384
load @ main.bundle.js:361
(anonymous) @ main.bundle.js:385
a @ main.bundle.js:385
(anonymous) @ main.bundle.js:385
c @ main.bundle.js:385
_tickCallback @ internal/process/next_tick.js:61
main.bundle.js:361 GET https://XXXXXXXXX.com/remote.php/webdav/%23blablabla/archive.bcup 503 ()
(anonymous) @ main.bundle.js:361
e.exports @ main.bundle.js:361
e.exports @ main.bundle.js:384
_tickCallback @ internal/process/next_tick.js:68
Promise.then (async)
u.request @ main.bundle.js:384
(anonymous) @ main.bundle.js:361
i.patchInline.e @ main.bundle.js:384
(anonymous) @ main.bundle.js:384
execute @ main.bundle.js:361
patchInline @ main.bundle.js:361
s @ main.bundle.js:384
e.exports @ main.bundle.js:384
request @ main.bundle.js:361
getFileContentsString @ main.bundle.js:385
getFileContents @ main.bundle.js:384
load @ main.bundle.js:361
(anonymous) @ main.bundle.js:385
a @ main.bundle.js:385
(anonymous) @ main.bundle.js:385
c @ main.bundle.js:385
_tickCallback @ internal/process/next_tick.js:61
main.bundle.js:361 GET https://XXXXXXXXX.com/remote.php/webdav/%23blablabla/archive2.bcup 503 ()
(anonymous) @ main.bundle.js:361
e.exports @ main.bundle.js:361
e.exports @ main.bundle.js:384
_tickCallback @ internal/process/next_tick.js:68
Promise.then (async)
u.request @ main.bundle.js:384
(anonymous) @ main.bundle.js:361
i.patchInline.e @ main.bundle.js:384
(anonymous) @ main.bundle.js:384
execute @ main.bundle.js:361
patchInline @ main.bundle.js:361
s @ main.bundle.js:384
e.exports @ main.bundle.js:384
request @ main.bundle.js:361
getFileContentsString @ main.bundle.js:385
getFileContents @ main.bundle.js:384
load @ main.bundle.js:361
(anonymous) @ main.bundle.js:385
a @ main.bundle.js:385
(anonymous) @ main.bundle.js:385
c @ main.bundle.js:385
_tickCallback @ internal/process/next_tick.js:61
main.bundle.js:361 GET https://XXXXXXXXX.com/remote.php/webdav/%23blablabla/archive2.bcup 503 ()
(anonymous) @ main.bundle.js:361
e.exports @ main.bundle.js:361
e.exports @ main.bundle.js:384
_tickCallback @ internal/process/next_tick.js:68
Promise.then (async)
u.request @ main.bundle.js:384
(anonymous) @ main.bundle.js:361
i.patchInline.e @ main.bundle.js:384
(anonymous) @ main.bundle.js:384
execute @ main.bundle.js:361
patchInline @ main.bundle.js:361
s @ main.bundle.js:384
e.exports @ main.bundle.js:384
request @ main.bundle.js:361
getFileContentsString @ main.bundle.js:385
getFileContents @ main.bundle.js:384
load @ main.bundle.js:361
(anonymous) @ main.bundle.js:385
a @ main.bundle.js:385
(anonymous) @ main.bundle.js:385
c @ main.bundle.js:385
_tickCallback @ internal/process/next_tick.js:61
main.bundle.js:361 GET https://XXXXXXXXX.com/remote.php/webdav/%23blablabla/archive2.bcup 503 ()
(anonymous) @ main.bundle.js:361
e.exports @ main.bundle.js:361
e.exports @ main.bundle.js:384
_tickCallback @ internal/process/next_tick.js:68
Promise.then (async)
u.request @ main.bundle.js:384
(anonymous) @ main.bundle.js:361
i.patchInline.e @ main.bundle.js:384
(anonymous) @ main.bundle.js:384
execute @ main.bundle.js:361
patchInline @ main.bundle.js:361
s @ main.bundle.js:384
e.exports @ main.bundle.js:384
request @ main.bundle.js:361
getFileContentsString @ main.bundle.js:385
getFileContents @ main.bundle.js:384
load @ main.bundle.js:361
(anonymous) @ main.bundle.js:385
a @ main.bundle.js:385
(anonymous) @ main.bundle.js:385
c @ main.bundle.js:385
_tickCallback @ internal/process/next_tick.js:61
```
I'm trying to load my archives stored on my Nextcloud throught WebDAV, on Fedora 30 and Buttercup 1.17.2

Thanks !

**Comment by aesthicc** [comment]
[817](https://github.com/buttercup/buttercup-desktop/issues/817)
[780](https://github.com/buttercup/buttercup-desktop/issues/780)

**Comment by perry-mitchell** [comment]
Stale. When using Nextcloud, make sure that you're:
 * Using the URL exposed within the UI settings
 * Using an app-specific password (Settings > Security > "Create new app password")
