### ISSUE TITLE
Possible corrupt Archive and how to try and decrypt any information out of it

### ISSUE THREAD

**Issue by m1ne5h** [buttercup/buttercup-desktop#936]
Hi, I've been using buttercup for a while with the archive on Dropbox, and using chrome to open archive etc. For about 2 weeks I've had issues doing this. I downloaded my archive locally and installed the Windows buttercup app and can not open my archive.
Considering that I can't open the archive using various chrome browsers on different laptops, as well as another Linux machine even using the Appimage of buttercup I think I have a corrupt archive, is there anyway I can decrypt the archive, as it has up to a hundred accounts in there, and I don't have a saved .csv file of this. 
Trying to open buttercup with the chrome extension results in the extension crashing.
Trying debug tools in Windows buttercup app and using a copied archive from buttercup I get:
`index.html:12 GET file:///C:/Program%20Files/Buttercup/resources/app.asar/dist/main.css net::ERR_FILE_NOT_FOUND
(anonymous) @ index.html:12
(anonymous) @ index.html:14`
Sources : file:///C:/Program%20Files/Buttercup/resources/app.asar/views/index.html
I get Paused before potential out-of-memory-crash with a call stack below it

Happy to provide more logs etc if you tell me what and how to do so?
Thanks

**Comment by m1ne5h** [comment]
Ubuntu system whilst trying to import archive from dropbox:
![Screenshot from 2020-08-13 14-01-57](https://user-images.githubusercontent.com/28604329/90138488-fda7e000-dd6e-11ea-9062-11d6f4502340.png)

Error from terminal window when I tried to open archive in desktop app and when the error in screenshot occurred
`[13:45:32:0715] [info] Checking for update
[13:45:32:0782] [error] Error: Error: ENOENT: no such file or directory, open '/opt/Buttercup/resources/app-update.yml'
    at j.B [as _captureStackTrace] (/opt/Buttercup/resources/app.asar/dist/app.js:206:151655)
    at new d (/opt/Buttercup/resources/app.asar/dist/app.js:206:181335)
    at /opt/Buttercup/resources/app.asar/dist/app.js:206:184424
    at t.AppImageUpdater._checkForUpdates (/opt/Buttercup/resources/app.asar/dist/app.js:71:19408)
    at t.AppImageUpdater.checkForUpdates (/opt/Buttercup/resources/app.asar/dist/app.js:71:18244)
    at ac (/opt/Buttercup/resources/app.asar/dist/app.js:414:122956)
    at Timeout.setTimeout (/opt/Buttercup/resources/app.asar/dist/app.js:414:132481)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

<--- Last few GCs --->

[5265:0xbf102b27000]   459798 ms: Mark-sweep 1645.6 (1653.9) -> 598.7 (606.9) MB, 189.3 / 0.1 ms  allocation failure GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x644cf0841fd]
Security context: 0x617d4ba2609 <String[7]: file://>
    1: E(aka E) [file:///opt/Buttercup/resources/app.asar/dist/main.bundle.js:~356] [pc=0x644cf3e5787](this=0x17895cd822e1 <undefined>,e=0x19d5df884779 <Uint8Array map = 0x591911e6251>,t=0,r=126227508)
    2: /* anonymous */ [file:///opt/Buttercup/resources/app.asar/dist/main.bundle.js:356] [bytecode=0x617d4be4129 offset=204](this=0x19d5df884779 <Uin...


`

**Comment by nickbe** [comment]
Seeing that no one could help or advise you with this for 24 days now I'm really wondering about how much sense it makes to entrust passwords to buttercup. 

I think would be very important to have a reliable and fail safe storage format. Maybe it would be more advisable to have each entry stored single file. That way at least only one part of the database gets corrupted and we wouldn' loose everything.

**Comment by sallar** [comment]
@nickbe we are only 2 developers and we are doing our best to support all of the clients and at the same time keep adding features that users are requesting. We are looking into every single issue there is, but at the end of the day this is open source software and like all open source software, it takes time for us to get to every issue. We are looking into this.

**Comment by perry-mitchell** [comment]
We won’t be storing entries in single files, there’s too much overhead and it simply doesn’t make sense from an architectural point of view- It’d be too slow. Having all properties encrypted in one vault is perfectly fine. Any issues with corruption are **not** representative of a bad format - simply an issue with encoding or decoding it.

As Sallar said - we’re doing most of this ourselves - if someone wants to contribute a fix or a feature, the entire platform would be thankful. We simply don’t have time to address every possible potentiality, we have to think of the long game and what the best use of our time is. Right now that’s getting things stable, without refactoring, and implementing our hosted platform so we can build sustainability around Buttercup.

**Comment by perry-mitchell** [comment]
@m1ne5h How big is your vault file? The out of memory issue is likely this: buttercup/buttercup-core#287, and it's probably because of the padding commands in the vault which were being erroneously added in large quantities. The only course here is to either open it and save it, thus purging the pad commands, or by exporting and re-importing it.

You could try exporting using our very basic [diag-cli](https://github.com/buttercup/diag-cli). This will also be restricted to the same memory limits our other apps are, but you may be able to extend the memory limit using node:

```shell
node --max-old-space-size=8192 bcup-diag-location/source/index.js inspect ~/my/vault.bcup
```

Where `bcup-diag-location` is the location where you installed the bcup diag tool. If inspect works, so should the export command.

It would be best to try and launch the desktop app with increased memory, but I'm not sure how you'd do this.

**Comment by perry-mitchell** [comment]
Closing due to inactivity.
